2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_setup.py:_flush():76] Configure stats pid to 12528
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_setup.py:_flush():76] Loading settings from /opt/ml/.config/wandb/settings
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_setup.py:_flush():76] Loading settings from /opt/ml/Facial_verification/wandb/settings
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'train.py'}
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_init.py:_log_setup():507] Logging user logs to /opt/ml/Facial_verification/wandb/run-20230812_121832-inoj3xyr/logs/debug.log
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_init.py:_log_setup():508] Logging internal logs to /opt/ml/Facial_verification/wandb/run-20230812_121832-inoj3xyr/logs/debug-internal.log
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_init.py:init():547] calling init triggers
2023-08-12 12:18:32,433 INFO    MainThread:12528 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-08-12 12:18:32,434 INFO    MainThread:12528 [wandb_init.py:init():596] starting backend
2023-08-12 12:18:32,434 INFO    MainThread:12528 [wandb_init.py:init():600] setting up manager
2023-08-12 12:18:32,438 INFO    MainThread:12528 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-08-12 12:18:32,443 INFO    MainThread:12528 [wandb_init.py:init():606] backend started and connected
2023-08-12 12:18:32,449 INFO    MainThread:12528 [wandb_init.py:init():705] updated telemetry
2023-08-12 12:18:32,463 INFO    MainThread:12528 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-08-12 12:18:32,845 ERROR   MainThread:12528 [wandb_init.py:init():764] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-08-12 12:18:32,947 ERROR   MainThread:12528 [wandb_init.py:init():1172] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/opt/conda/envs/insight/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/opt/conda/envs/insight/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-08-12 12:18:33,950 WARNING MsgRouterThr:12528 [router.py:message_loop():77] message_loop has been closed
